version: '3'

services:
  nginx:
    container_name: nginx-container
    build:
      context: ./app/docker/dev/nginx
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
  php-fpm:
    container_name: php83-fpm-container
    build:
      context: ./app/docker/dev/php-fpm
    volumes:
      - ./app:/app
  php-cli:
    build:
      context: ./app/docker/dev/php-cli
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
  postgres:
    image: postgres:16.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  node:
    container_name: node_container
    image: node:21.5-alpine3.18
    volumes:
      - ./app:/app
    working_dir: /app

volumes:
  postgres:
  composer:
