version: '3'

services:
  nginx:
    container_name: nginx-container
    build:
      context: ./app/docker/dev/nginx
    volumes:
      - ./app:/app
    restart: always
    ports:
      - "8080:80"
  php-fpm:
    container_name: php82-fpm-container
    restart: always
    build:
      context: ./app/docker/dev/php-fpm
    volumes:
      - ./app:/app
  php-cli:
    build:
      context: ./app/docker/dev/php-cli
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache

volumes:
  composer: