doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '16.1'
        charset: utf8
        default_table_options:
            charset: utf8
        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                type: php
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
