vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    users:
      uri_prefix: /images/users
      upload_destination: "%kernel.project_dir%/public/images/users"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    thumbnail:
      uri_prefix: /images/thumbnails
      upload_destination: "%kernel.project_dir%/public/images/thumbnails"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

